# Generated by Django 2.0.6 on 2020-05-04 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('good_name', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('content', models.TextField()),
                ('sell_num', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_good',
            },
        ),
        migrations.CreateModel(
            name='GoodCate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_cate_name', models.CharField(max_length=30)),
                ('parent_id', models.IntegerField()),
                ('level', models.IntegerField()),
            ],
            options={
                'db_table': 'tb_goodcate',
            },
        ),
        migrations.CreateModel(
            name='Purchase_records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('num', models.IntegerField()),
                ('address', models.CharField(max_length=80)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'tb_purchase_records',
            },
        ),
        migrations.AddField(
            model_name='good',
            name='good_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='operations.GoodCate'),
        ),
    ]
