# Generated by Django 2.0.6 on 2020-05-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('tel', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tb_employee',
            },
        ),
        migrations.CreateModel(
            name='ReturnSale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('data', models.DateTimeField()),
                ('num', models.IntegerField()),
                ('address', models.CharField(max_length=80)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'tb_returnsale',
            },
        ),
    ]
