# Generated by Django 2.0.6 on 2020-05-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_employee_returnsale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('sex', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('tel', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tb_employees',
            },
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
